### ISSUE TITLE
Y database

### ISSUE THREAD

**Issue by martinhaagmans** [unique379r/strspy#2]
Hi,

I am trying to create the Y-database, but I have not been able to do so.

From the README in the Y-str-prep folder:
- What should be in the < input motif repeats > file?
- Do I use v5 for single repeats and v4 for batch lists of repeats?

Autosomal worked great :)

Best,
Martin

**Comment by unique379r** [comment]
Hi Martin
Thanks for choosing the STRspy. 
Answer to your question: you dont need to prepare Y-STR, the package will be updated soon with STR-Y database same as autosomal. But if you need immediate, do let me know, will try to send it to you.

Thanks
Rupesh

**Comment by martinhaagmans** [comment]
Hi again,

would it be possible for you to send me the Y-STR database?

Thanks for your time,
Martin

**Comment by malmarri** [comment]
Hi @unique379r and @martinhaagmans, just wanted to ask if the Y-STR database is currently available?

Thanks,
M

**Comment by unique379r** [comment]
@malmarri 
It will be available soon with new publication. Along with improved and some new features of STRspy.

**Comment by martinhaagmans** [comment]
> Hi @unique379r and @martinhaagmans, just wanted to ask if the Y-STR database is currently available?
> 
> Thanks, M

Not to me.

**Comment by aa7400** [comment]
Hello,
Any updates on the Y-STR database? 
It is still not available.
