### ISSUE TITLE
Y-str database

### ISSUE THREAD

**Issue by aa7400** [unique379r/strspy#5]
Hello,
Any updates on the Y-STR database? 
It is still not available.
Best,
Ari

_Originally posted by @aa7400 in https://github.com/unique379r/strspy/issues/2#issuecomment-1951749376_

**Comment by unique379r** [comment]
Hi
Thank you for your interest in using STRspy. We are working on our next paper with STRspy v2.0 (including profiling of autosome and chrY). Once we submit the paper, we will make it avaiable for public. 

Thank you.
